from pathlib import Path
import json,os,time
from playwright.sync_api import sync_playwright
BASE=os.environ.get('SAMPLE_BASE','http://127.0.0.1:8765/sample-v2/')
out=Path('/tmp/voice-coach-qa');out.mkdir(parents=True,exist_ok=True)
report={'checks':[],'errors':[],'layouts':[],'slide_layouts':[]}
def ok(v,msg):
 if not v:raise AssertionError(msg)
 report['checks'].append(msg)
def persist(): (out/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
with sync_playwright() as p:
 browser=p.chromium.launch(args=['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
 page=browser.new_page(viewport={'width':1440,'height':900});page.on('pageerror',lambda e:report['errors'].append(str(e)))
 page.add_init_script("window.__deviceSpeech=0;if(window.speechSynthesis)window.speechSynthesis.speak=()=>{window.__deviceSpeech++;};")
 try:
  page.goto(BASE+'book.html?s=l1-inquiry',wait_until='networkidle');page.wait_for_function("document.documentElement.dataset.ready==='true'")
  ok(page.locator('.face-overlay,.mouth,.tongue').count()==0,'No synthetic mouth or face overlay in the living book')
  ok(page.locator('.character-figure img').count()==1,'Exactly one whole approved expression is rendered')
  for m in ['listen','explain','think','surprise','praise','encourage']:
   page.evaluate('(m)=>window.__sample.coach.mood(m)',m);page.wait_for_function("document.querySelector('.character-figure img').complete && document.querySelector('.character-figure img').naturalWidth===480")
   page.locator('.character-figure').screenshot(path=str(out/(m+'.png')))
  ok(True,'All six approved expression assets load at their shared dimensions')
  lib=page.evaluate('window.__sample.coach.library');ok(len(lib['playlists'])==20,'20 full-learning-page OmniVoice playlists')
  ok(all(p['clips'] for p in lib['playlists'].values()),'No empty full-reading playlist')
  ok(all(x.startswith('OmniVoice') for x in [c['engine'] for c in lib['clips'].values()]),'Every registered clip is generated by OmniVoice')
  page.locator('#auto').uncheck();page.locator('#sound[aria-pressed=false]').click() if page.locator('#sound[aria-pressed=false]').count() else None
  for id in ['l1-inquiry','l1-inquiry-record']:
   page.evaluate("id=>window.__sample.navigate(window.__sample.pages.findIndex(p=>p.id===id))",id);page.locator('#start').click();page.wait_for_function('window.__sample.coach.audio?.currentTime>0.05')
   ok('OmniVoice' in page.locator('#voice-kind').inner_text(),'Missing intro is now real OmniVoice: '+id)
   ok('/'+id+'.mp3' in page.evaluate('window.__sample.coach.audio.currentSrc'),'Correct introduction audio file '+id)
   page.screenshot(path=str(out/(id+'-playing.png')));page.locator('#start').click()
  page.evaluate("window.__sample.navigate(0)");page.locator('#auto').check();page.locator('#start').click();page.wait_for_function('window.__sample.coach.audio?.duration>1');page.evaluate('window.__sample.coach.audio.currentTime=window.__sample.coach.audio.duration-0.12');page.wait_for_function("document.querySelector('#workspace').classList.contains('active')")
  page.wait_for_function("document.querySelectorAll('#activity-content [data-order-id]').length===5")
  ok(page.locator('[data-order-id]').count()==5,'Actual audio ended event opens the five-object activity')
  page.locator('[data-prediction-reason]').fill('크기와 재료를 보고 다섯 물건을 비교했어요.');page.locator('[data-prediction-done]').click();page.wait_for_function('window.__lab?.state')
  # Deliberately wrong experimental procedure, only the generic voice is allowed.
  page.evaluate('window.__lab.setZero(0.3)');page.locator('[data-object=apple]').press('Enter');page.wait_for_function('window.__lab.state().settled');page.locator('[data-inquiry-reading]').fill('2.3');page.locator('[data-inquiry-record]').click();page.wait_for_function('window.__sample.coach.audio?.currentTime>0.05')
  ok('method-error.mp3' in page.evaluate('window.__sample.coach.audio.currentSrc'),'Generic method-error uses OmniVoice without naming calibration')
  ok('영점' not in page.locator('[data-inquiry-feedback]').inner_text(),'Experimental cause is not disclosed in the first feedback')
  page.locator('#sound').click();page.locator('[data-inquiry-record]').click();page.wait_for_timeout(250);ok(not page.evaluate('window.__sample.coach.playing'),'Sound-off prevents automatic feedback audio')
  page.locator('#close-activity').click();page.locator('#sound').click()
  page.evaluate("window.__sample.navigate(window.__sample.pages.findIndex(p=>p.id==='l1-future'))");page.locator('#read-text').click();page.wait_for_function('window.__sample.coach.audio?.currentTime>0.05');first=page.evaluate('window.__sample.coach.audio.currentSrc');page.evaluate('window.__sample.coach.audio.currentTime=window.__sample.coach.audio.duration-0.12');page.wait_for_function('(a)=>window.__sample.coach.audio?.currentSrc!==a && window.__sample.coach.audio?.currentTime>0.02',arg=first)
  ok(True,'Full-page reading advances through real OmniVoice clips')
  page.evaluate('window.__sample.navigate(0)');page.wait_for_timeout(300);ok(not page.evaluate('window.__sample.coach.playing'),'Page navigation cancels the previous reading queue')
  # All real generated clips are decoded, not just present in a manifest.
  dec=page.evaluate('''async()=>{const ctx=new AudioContext();const a=[];for(const [id,c] of Object.entries(window.__sample.coach.library.clips)){const r=await fetch(c.path);if(!r.ok)throw Error(id+' '+r.status);const b=await ctx.decodeAudioData(await r.arrayBuffer());if(b.duration<.1)throw Error(id);a.push({id,duration:b.duration});}await ctx.close();return a;}''');report['audio']=dec;ok(len(dec)==len(lib['clips']),'All registered OmniVoice audio files actually decode')
  ok(page.evaluate('window.__deviceSpeech===0'),'No browser/device TTS was invoked')
  # Failed audio cannot fall back to another voice or automatically open the lab.
  page.locator('#auto').check();page.route('**/audio/l1-inquiry.mp3',lambda r:r.abort());page.locator('#start').click();page.wait_for_timeout(500)
  ok(page.evaluate('window.__deviceSpeech===0'),'Failed audio does not invoke device TTS')
  ok(not page.locator('#workspace').evaluate("e=>e.classList.contains('active')"),'Failed audio does not advance the activity')
  page.unroute('**/audio/l1-inquiry.mp3')
  # Teaching and self-study are separate landscape scene behavior, not A4 redirects.
  page.goto(BASE+'class.html?mode=teach',wait_until='networkidle');page.wait_for_function("document.documentElement.dataset.ready==='true'")
  slides=page.evaluate('window.__class.slides');report['slides']=len(slides)
  ok(len([s for s in slides if s.get('question')])==18,'Landscape course contains all18 original questions exactly once')
  ok(len({s['page'] for s in slides})==20,'Landscape course includes all20 existing learning pages')
  i=next(i for i,s in enumerate(slides) if s['page']=='l1-structure');page.evaluate('i=>window.__class.navigate(i)',i)
  hidden=page.locator('.step-reveal:not(.revealed)').count();ok(hidden>1,'Teaching structure descriptions are initially hidden')
  page.locator('#class-next').click();ok(page.evaluate('window.__class.current')==i,'Next reveals one teaching explanation before changing slides')
  ok(page.locator('.step-reveal:not(.revealed)').count()==hidden-1,'Teaching reveal is one step at a time')
  page.locator('#class-notes-toggle').click();ok(page.locator('#class-notes').is_visible(),'Teacher notes are available separately');page.locator('#class-notes-toggle').click()
  for i,s in enumerate(slides):
   page.evaluate('i=>window.__class.navigate(i)',i)
   m=page.locator('#slide-body').evaluate('(e)=>({w:e.clientWidth,sw:e.scrollWidth,h:e.clientHeight,sh:e.scrollHeight})');report['slide_layouts'].append({'i':i,'id':s['id'],**m})
   if m['sw']>m['w']+3 or m['sh']>m['h']+4:page.screenshot(path=str(out/f'overflow-{i}.png'))
  ok(all(m['sw']<=m['w']+3 and m['sh']<=m['h']+4 for m in report['slide_layouts']),'All desktop teaching scenes fit without clipped content')
  i=next(i for i,s in enumerate(slides) if s.get('question',{} ) and s['question']['id']=='a2');page.evaluate('i=>window.__class.navigate(i)',i)
  page.locator('#class-mode').select_option('self');page.wait_for_function("window.__class?.mode==='self'")
  ok(not page.locator('#slide-body .teacher-answer').is_visible(),'Student scene does not inherit instructor answer visibility')
  page.locator('input[name=a2][value="2"]').check();page.locator('#slide-check').click();ok(page.evaluate('window.__class.results.a2.correct'),'Self-study answer is actually graded with the shared question model')
  page.locator('#class-sound').click() if page.locator('#class-sound').get_attribute('aria-pressed')=='true' else None
  page.screenshot(path=str(out/'self-answer.png'))
  self_layouts=[]
  for j,s in enumerate(slides):
   page.evaluate('j=>window.__class.navigate(j)',j)
   m=page.locator('#slide-body').evaluate('(e)=>({w:e.clientWidth,sw:e.scrollWidth,h:e.clientHeight,sh:e.scrollHeight})');self_layouts.append({'i':j,'id':s['id'],**m})
   if m['sw']>m['w']+3 or m['sh']>m['h']+4:page.screenshot(path=str(out/f'self-overflow-{j}.png'))
  report['self_slide_layouts']=self_layouts
  ok(all(m['sw']<=m['w']+3 and m['sh']<=m['h']+4 for m in self_layouts),'All desktop self-study scenes fit including response fields')
  page.goto(BASE+'book.html?s=l1-test-a',wait_until='networkidle');page.wait_for_function("document.documentElement.dataset.ready==='true'");ok(page.evaluate("window.__sample.answers.a2==='2'"),'Answer entered in self-study stays available in the eBook')
  # Fit both routes on common PC/tablet and phone sizes.
  for route in ['book.html?s=l1-inquiry','class.html?mode=self']:
   for w,h in [(1920,1080),(1366,768),(1280,720),(390,844)]:
    page.set_viewport_size({'width':w,'height':h});page.goto(BASE+route,wait_until='networkidle');page.wait_for_function("document.documentElement.dataset.ready==='true'");page.wait_for_timeout(200)
    x=page.evaluate('({sw:document.documentElement.scrollWidth,w:innerWidth,h:innerHeight})');report['layouts'].append({'route':route,**x})
    ok(x['sw']<=w+2,'Viewport fits '+route+' '+str(w)+'x'+str(h))
    control=page.locator('#next' if route.startswith('book') else '#class-next').bounding_box();ok(control and control['y']+control['height']<=h+1,'Bottom navigation remains visible '+str(w))
    page.screenshot(path=str(out/(('book' if route.startswith('book') else 'class')+f'-{w}.png')))
  ok(not report['errors'],'No uncaught browser errors');persist()
 except Exception as e:
  report['failure']=str(e)
  try:page.screenshot(path=str(out/'failure.png'),full_page=True)
  except Exception:pass
  raise
 finally:
  persist();browser.close()
