import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.MSG_PLAYWRIGHT_URL || 'playwright');
const root = new URL('../', import.meta.url);
const out = new URL('.proofs/', root);
await mkdir(out, { recursive: true });
const base = process.env.MSG_BASE_URL || 'http://127.0.0.1:4317';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1365, height: 1024 } });
const page = await context.newPage();
const errors = [], uploads = [], checks = [];
page.on('pageerror', e => errors.push(e.message));
page.on('request', r => { if (r.method() === 'POST' || r.method() === 'PUT') uploads.push(r.url()); });
const pass = name => { checks.push(name); console.log('PASS', name); };
const file = name => new URL(name, out).pathname.replace(/^\/(\w:)/, '$1');
await page.goto(base + '/student.html');
await page.locator('.teacher-rig image').evaluate(async el => { const img = new Image(); img.src = el.getAttribute('href'); await img.decode(); });
assert.equal(await page.locator('#teacher-answer').count(), 0);
assert.equal(await page.locator('#force').innerText(), '2 N');
await page.locator('#add-weight').click(); assert.equal(await page.locator('#force').innerText(), '3 N');
await page.locator('#add-weight').click(); assert.equal(await page.locator('#add-weight').isDisabled(), true);
await page.locator('#remove-weight').click(); await page.locator('#remove-weight').click();
pass('bounded spring controls with consistent units');
const before = await page.locator('#spring').innerHTML();
const boxBefore = await page.locator('#avatar').boundingBox();
await page.locator('#play').click();
const shapes = new Set();
for (let n = 0; n < 14; n++) { await page.waitForTimeout(130); shapes.add(await page.locator('.teacher-rig').getAttribute('data-mouth')); }
assert(shapes.size > 1);
assert.equal(await page.locator('#spring').innerHTML(), before);
const boxDuring = await page.locator('#avatar').boundingBox();
assert.equal(boxBefore.y, boxDuring.y);
await page.locator('#play').click(); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
await page.waitForTimeout(300); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
pass('mouth animation, pause closure, stable character and experiment geometry');
await page.locator('#play').click(); await page.waitForTimeout(250); await page.locator('#stop').click();
assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
assert.equal(await page.locator('#progress').evaluate(el => el.value), 0);
pass('resume and stop reset playback');
await page.locator('button[data-mood="surprise"]').click(); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'round');
await page.locator('button[data-mood="praise"]').click(); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mood'), 'praise');
await page.locator('button[data-mood="question"]').click(); assert.equal(await page.locator('.question-brow').evaluate(el => getComputedStyle(el).display), 'block');
await page.locator('button[data-mood="listen"]').click(); assert.equal(await page.locator('.closed-listen').evaluate(el => getComputedStyle(el).display), 'block');
await page.locator('button[data-mood="welcome"]').click();
await page.locator('#blink').click(); await page.waitForTimeout(30); assert(await page.locator('.teacher-rig').evaluate(el => el.classList.contains('blinking')));
pass('expression and blink controls');
await page.locator('#hint-button').click(); assert.equal(await page.locator('#hint').isVisible(), true);
await page.locator('[data-step="4"]').click(); await page.locator('[data-answer="2"]').click(); assert.match(await page.locator('#feedback').innerText(), /다시/);
await page.locator('[data-answer="3"]').click(); assert.match(await page.locator('#feedback').innerText(), /맞아요/);
pass('student hints and original sample question feedback');
await page.locator('[data-step="0"]').click();

// A synthetic tone with a silent middle section is a QA fixture, never a teacher voice.
const rate = 24000, seconds = 3, samples = rate * seconds, wav = Buffer.alloc(44 + samples * 2);
wav.write('RIFF', 0); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(rate, 24); wav.writeUInt32LE(rate * 2, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(samples * 2, 40);
for (let n = 0; n < samples; n++) { const t = n / rate, v = t < .9 || t > 1.8 ? Math.sin(t * 2 * Math.PI * 190) * .16 : 0; wav.writeInt16LE(Math.round(v * 32767), 44 + n * 2); }
await writeFile(new URL('qa-tone-not-a-voice.wav', out), wav);
await page.locator('#audio-file').setInputFiles({ name: 'qa-tone-not-a-voice.wav', mimeType: 'audio/wav', buffer: wav });
await page.locator('#play').click(); await page.waitForTimeout(300);
assert.notEqual(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
await page.waitForTimeout(1000); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
await page.waitForTimeout(850); assert.notEqual(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
await page.waitForTimeout(1100); assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
assert.equal(uploads.length, 0);
pass('local audio activity, silence, ending, and zero uploads');
await page.locator('#demo-mode').click();
for (const width of [1365, 390, 320]) {
  await page.setViewportSize({ width, height: 950 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: file(`student-${width}.png`), fullPage: true });
}
pass('desktop, 390px and 320px without horizontal overflow');
await page.setViewportSize({ width: 1365, height: 950 });
await page.goto(base + '/lecture.html');
assert.equal(await page.locator('#teacher-answer').isVisible(), false);
await page.locator('#reveal').click(); assert.equal(await page.locator('#teacher-answer').isVisible(), true);
await page.locator('#next').click(); assert.equal(await page.locator('#teacher-answer').isVisible(), false);
assert.equal(await page.locator('#teacher-answer').innerText(), '');
await page.locator('#previous').click();
await page.screenshot({ path: file('lecture-desktop.png'), fullPage: true });
pass('separate lecture mode with teacher-controlled reveal and slide reset');
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.locator('#play').click(); await page.waitForTimeout(450);
assert.equal(await page.locator('.teacher-rig').getAttribute('data-mouth'), 'closed');
assert(!(await page.locator('.teacher-rig').evaluate(el => el.classList.contains('blinking'))));
await page.locator('#stop').click();
pass('reduced-motion mode remains usable');
await page.emulateMedia({ media: 'print', reducedMotion: 'reduce' });
await page.screenshot({ path: file('print-preview.png'), fullPage: true });
await page.emulateMedia({ media: 'screen', reducedMotion: 'no-preference' });
const response = await page.request.get(base + '/.private/reference.wav'); assert.equal(response.status(), 403);
pass('private directory not exposed by preview server');
assert.deepEqual(errors, []);
pass('zero browser JavaScript errors');
await writeFile(new URL('browser-report.json', out), JSON.stringify({ checks, errors, uploads, timestamp: new Date().toISOString() }, null, 2));
await context.close();

// Short silent demo recording for review, explicitly not voice synthesis.
const recording = await browser.newContext({ viewport: { width: 1280, height: 960 }, recordVideo: { dir: file('video/'), size: { width: 1280, height: 960 } } });
const demo = await recording.newPage(); await demo.goto(base + '/character.html');
await demo.locator('.character-tools').evaluate(el => el.removeAttribute('open'));
await demo.locator('#play').click(); await demo.waitForTimeout(16000);
await demo.locator('#stop').click(); await demo.waitForTimeout(500);
await demo.screenshot({ path: file('character-demo.png') });
await recording.close();
console.log('VIDEO', await demo.video().path());
await browser.close();
