import {pages,questions,gradeGroups,narration,lessonNames} from './content.js';
import {esc} from './graphics.js';
import {qrById} from './qr-map.js';
import {gradeQuestion} from './physics.js';
import {mountActivity,activityNames} from './activities.js';
import {mountReview,concepts} from './review.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BASE_KEY='msg-source-sample-v2:';
let writable=true;try{localStorage.setItem(BASE_KEY+'probe','1');localStorage.removeItem(BASE_KEY+'probe');}catch{writable=false;}
const memory=new Map();
function load(k,d){try{const x=localStorage.getItem(BASE_KEY+k);return x===null?(memory.get(k)??d):JSON.parse(x);}catch{return memory.get(k)??d;}}
function save(k,v){if(k==='graph-assessment-result'){results.b12={correct:v.correct??v,value:load('graph-assessment',[]),time:Date.now()};memory.set('results',results);try{localStorage.setItem(BASE_KEY+'results',JSON.stringify(results));}catch{}}memory.set(k,v);try{localStorage.setItem(BASE_KEY+k,JSON.stringify(v));return true;}catch{writable=false;return false;}}
let inkMode=false,inkPointer=null,activeKind='book';const inks=new Map();
let current=0,book=null,activity=null,activityToken=0,voiceToken=0,voiceResolve=null,audio=null,utterance=null,started=false,reading=false;
let wantSpread=load('spread',true),motion=load('motion',true),sound=load('sound',true),showCharacter=load('character',true),isTeacher=load('teacher',false),rebuilding=false;
const answers=load('answers',{}),results=load('results',{});
let files={};
// A generation manifest is required before advertising a clip as an OmniVoice result.
try{files=await fetch('./audio/narration-manifest.json').then(r=>r.ok?r.json():{});}catch{}
let toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
let paperSerial=0;
function scopeGraphics(html){const pageKey='v'+paperSerial++;let j=0;return html.replace(/<svg[\s\S]*?<\/svg>/g,s=>{const pre=pageKey+'-'+j+++'-';const ids=[...s.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);for(const id of ids){s=s.replaceAll('id="'+id+'"','id="'+pre+id+'"').replaceAll('url(#'+id+')','url(#'+pre+id+')');}return s;});}
function paper(p,i){return `<article class="paper has-lab-qr ${p.dense?'dense':''} ${p.assessment?'assessment':''}" data-book-page="${i}" data-layout-page="${p.layoutIndex??i}" data-source="${p.source.join(',')}"><div class="page-top"><strong>${String(p.lesson).padStart(2,'0')} / ${lessonNames[p.lesson]}</strong><em>SMART SCIENCE</em></div><a class="lab-qr" href="${qrById[p.id].url}" target="_blank" rel="noopener" aria-label="${p.lesson}차시 관련 활동 열기"><img src="./qr/${p.id}.png" alt="관련 실험·활동 QR"><span>실험 · 활동 열기</span></a><div class="page-heading"><div class="eyebrow">${p.kicker}</div><h1>${p.title}</h1><p class="page-lead">${p.lead}</p></div><form class="page-body" aria-label="교재 답안 ${i+1}">${scopeGraphics(p.body)}</form><footer class="page-foot"><span>MSG · ${p.lesson}차시 / ${p.added?'추가 도입 탐구 · 본책 10쪽 연계':'본책 '+p.source.join('·')+'쪽'}</span><span>${isTeacher?'교사용':'학생용'} <strong>${String(i+1).padStart(2,'0')}</strong></span></footer></article>`;}
function printBuild(){ $('#print-root').innerHTML=pages.map(paper).join('');if(isTeacher)$('#print-root').querySelectorAll('[data-reveal]').forEach(el=>el.textContent=el.dataset.reveal); }
function isSpread(){return wantSpread&&innerWidth>1000&&!$('#workspace').classList.contains('active');}
function fit(){const space=$('#book-space'),wrap=$('#book-transform');if(!space||!wrap)return;const w=isSpread()?1588:794,h=1123;const scale=Math.max(.05,Math.min((space.clientWidth-16)/w,(space.clientHeight-14)/h));wrap.style.width=w+'px';wrap.style.height=h+'px';wrap.style.transform=`translate(-50%,-50%) scale(${scale})`;$('#fit-info').textContent=`전체 지면 ${Math.round(scale*100)}% · 본문 크게로 확대`;}
function restoreFields(root=document){root.querySelectorAll('[data-answer-field]').forEach(el=>{const v=answers[el.name];if(el.type==='radio')el.checked=String(v)===el.value;else if(v!==undefined)el.value=v;});}
function updateMeta(){drawInk();const p=pages[current];$('#current-section').textContent=`${p.lesson}차시 · ${p.kicker.split('·')[1]||p.kicker}`;$('#page-source').textContent=`본책 ${p.source.join('·')}쪽 · 재편집 ${current+1}/${pages.length}`;$('#page-select').value=current;$('#prev').disabled=current===0;$('#next').disabled=current>=pages.length-1;$$('[data-lesson]').forEach(b=>b.classList.toggle('selected',+b.dataset.lesson===p.lesson));$('#teacher-guide').textContent=p.teacher;$('#teacher-guide').hidden=!isTeacher;$('#coach-copy').textContent=files[p.id]?.text||narration[p.id].text;$('#lesson-state').textContent=p.assessment?'생각하고 답할 때는 자동으로 넘기지 않습니다.':'해설 → 활동 → 관찰 → 교재로 돌아오기';save('page',current);}
function buildBook(){rebuilding=true;const old=current;book?.destroy();$('#book-transform').innerHTML='<div id="flipbook"></div>';const el=$('#flipbook');el.style.width=(isSpread()?1588:794)+'px';el.style.height='1123px';el.innerHTML=pages.map(paper).join('');restoreFields(el);
 book=new St.PageFlip(el,{width:794,height:1123,size:'fixed',autoSize:false,minWidth:794,maxWidth:794,minHeight:1123,maxHeight:1123,usePortrait:!isSpread(),showCover:false,startPage:old,flippingTime:500,maxShadowOpacity:.2,useMouseEvents:false,clickEventForward:true,disableFlipByClick:true,showPageCorners:false,mobileScrollSupport:true});
 book.loadFromHTML(el.querySelectorAll('.paper'));book.on('flip',e=>{if(rebuilding)return;current=Math.min(pages.length-1,e.data);updateMeta();restoreFields(el);});
 book.turnToPage(old);current=old;fit();updateMeta();rebuilding=false;
}
function stopVoice(){voiceToken++;audio?.pause();if(audio){audio.removeAttribute('src');audio.load();}audio=null;if(window.speechSynthesis)speechSynthesis.cancel();utterance=null;voiceResolve?.(false);voiceResolve=null;document.body.classList.remove('talking');reading=false;$('#start').textContent=started?'▶ 해설 다시 듣기':'▶ 수업 시작';}
async function say(text,clipId=null){stopVoice();$('#coach-copy').textContent=text;if(!sound||document.hidden)return false;const token=voiceToken;reading=true;$('#start').textContent='Ⅱ 해설 멈추기';document.body.classList.add('talking');
 return new Promise(resolve=>{voiceResolve=resolve;let done=false;const finish=ok=>{if(done)return;done=true;if(token===voiceToken){document.body.classList.remove('talking');reading=false;$('#start').textContent='▶ 해설 다시 듣기';voiceResolve=null;}resolve(ok&&token===voiceToken);};
  const native=()=>{if(token!==voiceToken)return finish(false);if(!('speechSynthesis' in window)){toast('이 브라우저에서는 기기 음성을 지원하지 않습니다. 해설 문장을 읽어 주세요.');$('#voice-kind').textContent='음성 미지원 · 해설 텍스트';return finish(false);}$('#voice-kind').textContent='기기 한국어 음성 · OmniVoice와 구분';utterance=new SpeechSynthesisUtterance(text);utterance.lang='ko-KR';utterance.rate=.92;const v=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ko'));if(v)utterance.voice=v;utterance.onend=()=>finish(true);utterance.onerror=()=>{toast('기기 음성을 재생하지 못했습니다. 해설 텍스트는 계속 표시합니다.');finish(false);};speechSynthesis.speak(utterance);};
  if(clipId&&files[clipId]?.path){audio=new Audio(new URL(files[clipId].path,import.meta.url).href);$('#voice-kind').textContent='우루사쌤 · OmniVoice 생성 해설';audio.onended=()=>finish(true);audio.onerror=()=>{audio=null;native();};audio.play().catch(()=>{audio=null;native();});}else native();
 });
}
async function narrateCurrent(){started=true;if(!sound){if($('#auto').checked&&!pages[current].assessment)await openActivity(pages[current].action,true);return;}const p=pages[current],i=current;const completed=await say(files[p.id]?.text||narration[p.id].text,p.id);if(completed&&current===i&&$('#auto').checked&&!p.assessment)await openActivity(p.action,true);}
function readFull(){const p=pages[current],temp=document.createElement('div');temp.innerHTML=p.body;temp.querySelectorAll('svg,button,.teacher-answer,input,select').forEach(e=>e.remove());started=true;say(p.title.replace('\n',' ')+'。'+temp.textContent.replace(/\s+/g,' '));}
async function openActivity(kind,auto=false,custom=null){inkOff();activeKind=kind;drawInk();stopVoice();activityToken++;const token=activityToken;activity?.destroy();activity=null;window.__lab=null;const wasActive=$('#workspace').classList.contains('active');$('#workspace').classList.add('active');$('#activity').setAttribute('aria-hidden','false');$('#activity-title').textContent=activityNames[kind]||'개념 다시 확인';$('#activity-kicker').textContent=['watch','balance','spring-film'].includes(kind)?'ACTUAL FOOTAGE · 실제 기록영상':'SMART LAB · 교재 연계 활동';$('#activity-status').textContent='';$('#activity-content').innerHTML='';if(!wasActive)buildBook();
 const ctx={say,status:t=>$('#activity-status').textContent=t,load,save,setLab:l=>window.__lab=l,auto,open:openActivity,writable};
 if(custom){activity=custom($('#activity-content'),ctx);return;}
 if(kind==='source'){const p=pages[current];$('#activity-content').innerHTML=`<div class="source-view"><div class="source-tabs">${p.source.map(n=>`<button data-source-page="${n}">본책 ${n}쪽</button>`).join('')}</div><img src="./source/p${p.source[0]}.webp" alt="원본 교재 ${p.source[0]}쪽"></div>`;$('#activity-content').querySelectorAll('[data-source-page]').forEach(b=>b.onclick=()=>{$('#activity-content img').src=`./source/p${b.dataset.sourcePage}.webp`;$('#activity-content img').alt=`원본 교재 ${b.dataset.sourcePage}쪽`;});return;}
 if(kind==='reading'){$('#activity-content').innerHTML='<div class="large-reading">'+paper(pages[current],current)+'</div>';restoreFields($('#activity-content'));return;}
 if(kind==='credits'){credits();return;}
 if(kind==='assessment'){const p=pages[current];$('#activity-content').innerHTML='<div class="large-reading">'+paper(p,current)+'</div>';restoreFields($('#activity-content'));return;}
 try{const inst=await mountActivity(kind,$('#activity-content'),ctx);if(token!==activityToken)inst?.destroy();else activity=inst;}catch(e){$('#activity-content').innerHTML='<div class="large-reading"><h3>활동을 열지 못했습니다.</h3><p>'+esc(e.message)+'</p></div>';console.error(e);}
}
function closeActivity(){inkOff();activeKind='book';drawInk();stopVoice();activityToken++;activity?.destroy();activity=null;window.__lab=null;$('#activity-content').innerHTML='';$('#activity').setAttribute('aria-hidden','true');$('#workspace').classList.remove('active');buildBook();}
function navigate(i,{animated=false}={}){if(i<0||i>=pages.length)return;inkOff();stopVoice();if($('#workspace').classList.contains('active'))closeActivity();const old=current;current=i;const sameSpread=isSpread()&&Math.floor(old/2)===Math.floor(i/2);
 if(animated&&motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!sameSpread){book.flip(i);setTimeout(()=>{current=i;updateMeta();},550);}else{book.turnToPage(i);current=i;updateMeta();}
 $('#voice-kind').textContent=started?'해설 다시 듣기로 시작합니다.':'소리는 수업 시작 후 재생됩니다.';
}
function collectField(el){answers[el.name]=el.value;save('answers',answers);$$(`[data-answer-field][name="${CSS.escape(el.name)}"]`).forEach(other=>{if(other!==el){if(other.type==='radio')other.checked=other.value===el.value;else other.value=el.value;}});}
function valueFor(q){if(q.kind==='graph')return load('graph-assessment',[]);return Array.isArray(q.answer)?q.answer.map((_,i)=>answers[q.id+'-'+i]??''):answers[q.id]??'';}
function grade(group){const qs=gradeGroups[group];if(!qs)return;const blank=qs.find(q=>{const v=valueFor(q);return Array.isArray(v)?v.some(x=>!String(x).trim()):!String(v).trim();});if(blank){toast(`${blank.n}번의 답을 먼저 써 주세요.`);return;}
 qs.forEach(q=>results[q.id]={correct:gradeQuestion(q,valueFor(q)),value:valueFor(q),time:Date.now()});save('results',results);openActivity('assessment',false,(host,ctx)=>{host.innerHTML=`<div class="concept-review"><div class="eyebrow">원본 일일평가 · 제출한 답</div><h3>${qs.filter(q=>results[q.id].correct).length} / ${qs.length} 문항 정답</h3>${qs.map(q=>`<section class="result-item"><b>${q.n}번 · ${results[q.id].correct?'맞았어요':'다시 살펴봐요'}</b><p>${q.why}</p><button data-review="${q.concept}">${concepts[q.concept][0]} · 확인 질문</button><button data-related="${concepts[q.concept][1]}">관련 실험</button></section>`).join('')}<p>오답 하나로 오개념을 단정하지 않고, 이유 확인과 다른 문제로 다시 살핍니다.</p></div>`;host.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review));host.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>openActivity(b.dataset.related));return {destroy(){}};});}
function openReview(concept){return openActivity('assessment',false,(host,ctx)=>mountReview(host,concept,ctx));}
function credits(){ $('#activity-content').innerHTML=`<div class="credits"><h3>교재와 샘플 범위</h3><p>《초과심_물리》 본책 10–21쪽을 1·2차시, 추가 도입 2쪽과 재편집 18쪽으로 구성했습니다. 원본 쪽의 그림·표·문제를 본책 대조에서 확인할 수 있습니다. 원본의 역사·미래 서술과 과학적 보완 설명은 지면에서 구분합니다.</p><h3>가져온 코드</h3><p><a href="https://github.com/Nodlik/StPageFlip" target="_blank" rel="noopener">StPageFlip 2.0.7</a> · MIT · 책 넘김<br><a href="https://github.com/mrdoob/three.js" target="_blank" rel="noopener">Three.js 0.184.0 / OrbitControls</a> · MIT · 3D·카메라. 배포본에 원문 라이선스를 포함했습니다.</p><h3>광고 없는 실제 영상</h3><p><a href="https://commons.wikimedia.org/wiki/File:HowaWatchWork1949.ogv" target="_blank" rel="noopener">How a Watch Works (1949)</a> · Handy (Jam) Organization / Hamilton Watch Company · Prelinger Archives · Public Domain. 5:42–6:21, 11:20–11:47 발췌, 원음 제거. 원본이 저해상도인 역사 기록입니다.</p><p><a href="https://commons.wikimedia.org/wiki/File:Hookeslawexample.ogv" target="_blank" rel="noopener">Hookeslawexample</a> · Walter Lewin / MIT 8.01 · <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noopener">CC BY 3.0</a> · 0:29–0:43 발췌, 원음 제거, 출력 규격 맞춤. 이 영상은 관찰용이며 본책의 10·20·30 g 실험값을 증명하는 영상이 아닙니다.</p><h3>직접 만든 부분</h3><p>교재를 재편집한 지면, 벡터 도해, 용수철저울의 모델, 원본 평가의 웹 입력, 그래프 활동, 확인·유사문제와 수업 연결입니다. 물리 계산은 이상적인 용수철의 힘·변형·감쇠를 사용하며 <a href="https://www.myphysicslab.com/springs/single-spring-en.html" target="_blank" rel="noopener">myPhysicsLab의 용수철 설명</a>을 참조했습니다. 해당 사이트의 화면이나 프로그램 전체를 가져온 것은 아닙니다.</p><h3>음성</h3><p>생성 확인된 음성에는 OmniVoice로 표시합니다. 전체 본문 읽기와 즉석 확인 멘트는 기기 한국어 음성으로 별도 표시합니다. 실제 강사의 생방송·직접 녹음과 구분되는 합성 음성입니다.</p><h3>샘플 기록</h3><p>답안과 활동 기록은 이 브라우저의 localStorage에만 저장합니다. 학생 이름·연락처를 수집하지 않으며 기록을 서버에 전송하지 않습니다. 모든 기기 간 기록 동기화는 이 샘플의 범위 밖입니다.</p><h3>원본 보존과 교사용 주석</h3><p>p17의 ‘반비례’, p14의 역사 연대와 성능 수치는 원문 서술을 보존하고 주석으로 구분했습니다. 원문을 임의로 바꿔 정답으로 확정하지 않습니다.</p></div>`;}
$('#page-select').innerHTML=pages.map((p,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${p.lesson}차시 · ${p.kicker.split('·').at(-1).trim()}</option>`).join('');
const entryParams=new URLSearchParams(location.search);
const namedPage=pages.findIndex(p=>p.id===(entryParams.get('section')||entryParams.get('s')));
current=namedPage>=0?namedPage:Math.max(0,Math.min(pages.length-1,Number(entryParams.get('page')||load('page',0))));
if(!Number.isFinite(current))current=0;
document.body.classList.toggle('hide-character',!showCharacter);document.body.classList.toggle('teacher-mode',isTeacher);$('#character').setAttribute('aria-pressed',showCharacter);$('#character').textContent=showCharacter?'우루사쌤 표시':'우루사쌤 숨김';$('#teacher').setAttribute('aria-pressed',isTeacher);$('#sound').setAttribute('aria-pressed',sound);$('#sound').textContent=sound?'소리 켬':'소리 끔';$('#motion').setAttribute('aria-pressed',motion);$('#motion').textContent=motion?'책넘김 켬':'책넘김 끔';$('#spread').setAttribute('aria-pressed',wantSpread);$('#spread').textContent=wantSpread?'펼침 보기':'한 쪽 보기';
printBuild();buildBook();
$('#start').onclick=()=>reading?stopVoice():narrateCurrent();$('#read-text').onclick=readFull;
$('#sound').onclick=()=>{sound=!sound;save('sound',sound);$('#sound').setAttribute('aria-pressed',sound);$('#sound').textContent=sound?'소리 켬':'소리 끔';if(!sound)stopVoice();};
$('#prev').onclick=()=>navigate(current-1,{animated:true});$('#next').onclick=()=>navigate(current+1,{animated:true});$('#page-select').onchange=e=>navigate(+e.target.value);$$('[data-lesson]').forEach(b=>b.onclick=()=>navigate(pages.findIndex(p=>p.lesson===+b.dataset.lesson)));
$('#spread').onclick=()=>{wantSpread=!wantSpread;save('spread',wantSpread);$('#spread').setAttribute('aria-pressed',wantSpread);$('#spread').textContent=wantSpread?'펼침 보기':'한 쪽 보기';buildBook();};
$('#motion').onclick=()=>{motion=!motion;save('motion',motion);$('#motion').setAttribute('aria-pressed',motion);$('#motion').textContent=motion?'책넘김 켬':'책넘김 끔';};
$('#teacher').onclick=()=>{isTeacher=!isTeacher;save('teacher',isTeacher);document.body.classList.toggle('teacher-mode',isTeacher);$('#teacher').setAttribute('aria-pressed',isTeacher);$('#teacher').textContent=isTeacher?'학생용':'교사용';printBuild();buildBook();updateMeta();};
$('#character').onclick=()=>{showCharacter=!showCharacter;save('character',showCharacter);document.body.classList.toggle('hide-character',!showCharacter);$('#character').setAttribute('aria-pressed',showCharacter);$('#character').textContent=showCharacter?'우루사쌤 표시':'우루사쌤 숨김';fit();};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();fit();}catch{toast('브라우저 전체화면 권한이 없습니다. 현재 화면 맞춤은 유지합니다.');}};
$('#print').onclick=()=>{printBuild();window.print();};$('#source').onclick=()=>openActivity('source');$('#credits').onclick=()=>openActivity('credits');$('#focus-reading').onclick=()=>openActivity('reading');$('#close-activity').onclick=closeActivity;
document.addEventListener('submit',e=>e.preventDefault());
document.addEventListener('input',e=>{if(e.target.matches('[data-answer-field]'))collectField(e.target);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-grade],[data-reveal],[data-quick]');if(!b||b.closest('#print-root'))return;if(b.dataset.action){const page=b.closest('[data-book-page]');if(page){current=+page.dataset.bookPage;updateMeta();}openActivity(b.dataset.action);}if(b.dataset.grade)grade(b.dataset.grade);if(b.dataset.reveal){b.textContent=b.dataset.reveal;toast('탄성: 원래 모양으로 돌아가려는 성질');}if(b.dataset.quick){const r=b.closest('.inquiry').querySelector('.quick-result');r.textContent=b.dataset.quick==='비례'?'표와 그래프에서 비례 관계를 확인했어요.':'같은 배수로 늘어나는 관계인지 다시 살펴보세요.';}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#workspace').classList.contains('active'))closeActivity();else stopVoice();return;}if(e.target.closest('input,select,textarea,button,a')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='ArrowRight')navigate(current+1,{animated:true});if(e.key==='ArrowLeft')navigate(current-1,{animated:true});});
const ro=new ResizeObserver(fit);ro.observe($('#book-space'));let lastCompact=innerWidth<=1000;addEventListener('resize',()=>{const compact=innerWidth<=1000;if(compact!==lastCompact){lastCompact=compact;buildBook();}else fit();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopVoice();document.querySelectorAll('video').forEach(v=>v.pause());}});addEventListener('pagehide',()=>{stopVoice();activity?.destroy();ro.disconnect();});
if(!writable)toast('이 브라우저는 기록을 저장하지 못합니다. 중복 방지를 위해 새 유사문제 선택은 중단합니다.');

const ink=$('#ink-layer');
function inkKey(){return current+':'+activeKind;}
function drawInk(){const layer=$('#ink-layer');if(!layer)return;layer.innerHTML=(inks.get(inkKey())||[]).map(pts=>`<polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#bd493d" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>`).join('');}
function inkOff(){inkMode=false;inkPointer=null;$('#ink-layer')?.classList.remove('writing');$('#pen')?.setAttribute('aria-pressed','false');if($('#pen'))$('#pen').textContent='펜 판서';}
$('#pen').onclick=()=>{inkMode=!inkMode;inkPointer=null;ink.classList.toggle('writing',inkMode);$('#pen').setAttribute('aria-pressed',String(inkMode));$('#pen').textContent=inkMode?'실험 조작으로':'펜 판서';if(inkMode)toast('판서 모드: 실험 조작을 잠급니다. 펜 버튼을 다시 누르면 조작합니다.');};
$('#ink-undo').onclick=()=>{inks.get(inkKey())?.pop();drawInk();};$('#ink-clear').onclick=()=>{inks.delete(inkKey());drawInk();};
function inkPoint(e){if(inkPointer!==e.pointerId)return;const b=ink.getBoundingClientRect();const pts=inks.get(inkKey());if(!pts?.length)return;pts.at(-1).push([Math.round((e.clientX-b.x)/b.width*1000),Math.round((e.clientY-b.y)/b.height*1000)]);drawInk();}
ink.addEventListener('pointerdown',e=>{if(!inkMode||inkPointer!==null)return;e.preventDefault();inkPointer=e.pointerId;ink.setPointerCapture(e.pointerId);const strokes=inks.get(inkKey())||[];strokes.push([]);inks.set(inkKey(),strokes);inkPoint(e);});ink.addEventListener('pointermove',inkPoint);['pointerup','pointercancel','lostpointercapture'].forEach(t=>ink.addEventListener(t,()=>{inkPointer=null;}));
window.__sample={pages,questions,answers,results,navigate,open:openActivity,close:closeActivity,grade,printBuild,get current(){return current},get book(){return book},get writable(){return writable},save,load};
document.documentElement.dataset.ready='true';

// QR deep links open the matching activity, not a menu. No unsolicited audio.
if(entryParams.get('activity')&&activityNames[entryParams.get('activity')])openActivity(entryParams.get('activity'));
else if(entryParams.get('lab')==='1')openActivity(pages[current].action);
