import {pages,questions,narration} from './content.js';
import {buildClassSlides} from './class-content.js';
import {createCoach} from './coach.js';
import {mountActivity,activityNames} from './activities.js?v=urusaem-2';
import {gradeQuestion} from './physics.js';
import {esc} from './graphics.js';
const $=s=>document.querySelector(s),KEY='msg-source-sample-v2:',memory=new Map();
let writable=true;try{localStorage.setItem(KEY+'probe','1');localStorage.removeItem(KEY+'probe');}catch{writable=false;}
function load(k,d){try{const v=localStorage.getItem(KEY+k);return v===null?(memory.get(k)??d):JSON.parse(v);}catch{return memory.get(k)??d;}}
function save(k,v){memory.set(k,v);try{localStorage.setItem(KEY+k,JSON.stringify(v));}catch{writable=false;}if(k==='graph-assessment-result'){results.b12={correct:v.correct??v,value:load('graph-assessment',[]),time:Date.now()};save('results',results);}return writable;}
const params=new URLSearchParams(location.search),teach=params.get('mode')!=='self',slides=buildClassSlides();
const answers=load('answers',{}),results=load('results',{});
let current=Math.max(0,slides.findIndex(s=>s.id===params.get('slide'))),active=null,token=0,started=false,sound=load('sound',true),pen=false,strokes=[],ptr=null;
if(current===0&&params.has('s')){const i=slides.findIndex(s=>s.page===params.get('s'));if(i>=0)current=i;}
const coach=createCoach({figure:$('.character-figure'),caption:$('#coach-copy'),label:$('#voice-kind'),onState:s=>{$('#class-speak').textContent=s.playing?'Ⅱ 해설 멈추기':'▶ 우루사쌤 해설';},onError:()=>{}});
coach.setEnabled(sound);
function message(t){$('#class-message').hidden=false;$('#class-message').textContent=t;clearTimeout(message.timer);message.timer=setTimeout(()=>$('#class-message').hidden=true,4500);}
function currentPage(){return pages.find(p=>p.id===slides[current].page);}
function fit(){const host=$('.landscape-space'),slide=$('.landscape');if(innerWidth<=760){slide.style.transform='none';return;}const s=Math.max(.1,Math.min((host.clientWidth-12)/1280,(host.clientHeight-12)/720));slide.style.transform=`translate(-50%,-50%) scale(${s})`;}
function restore(root){root.querySelectorAll('[data-answer-field]').forEach(e=>{const v=answers[e.name];if(e.type==='radio')e.checked=String(v)===e.value;else if(v!==undefined)e.value=v;});}
function speechText(p){return coach.library.clips[p.id]?.text||narration[p.id].text;}
function next(){const h=$('#slide-body .step-reveal:not(.revealed)');if(teach&&h){h.classList.add('revealed');h.scrollIntoView({block:'nearest',behavior:'smooth'});coach.mood('explain');updateReveal();return;}if(current<slides.length-1)navigate(current+1);}
function updateReveal(){const total=$('#slide-body').querySelectorAll('.step-reveal').length,left=$('#slide-body').querySelectorAll('.step-reveal:not(.revealed)').length;$('#slide-reveal').hidden=!teach||!left;$('#slide-reveal').textContent='설명 한 단계 열기 ('+(total-left)+'/'+total+')';$('#class-next').textContent=teach&&left?'답·설명 열기 →':current===slides.length-1?'마지막 장':'다음 →';}
function prepareSlide(){const body=$('#slide-body'),s=slides[current];
 body.querySelectorAll('.teacher-answer').forEach(e=>{if(teach)e.classList.add('step-reveal');});
 if(teach){body.querySelectorAll('dd,.definition [data-reveal],.conclusion p').forEach(e=>{e.classList.add('step-reveal');if(e.dataset.reveal)e.textContent=e.dataset.reveal;});}
 body.querySelectorAll('.write-lines').forEach((e,i)=>{if(teach){e.remove();return;}const key='class-thought:'+s.id+':'+i;const wrap=document.createElement('div');wrap.className='self-reflect';wrap.innerHTML=`<label>내 생각<textarea class="thought-input" rows="2" aria-label="내 생각"></textarea></label><button type="button" class="class-inline-link">내 생각 기록</button><p role="status"></p>`;wrap.querySelector('textarea').value=load(key,'');wrap.querySelector('textarea').oninput=x=>save(key,x.target.value);wrap.querySelector('button').onclick=()=>{const v=wrap.querySelector('textarea').value.trim();wrap.querySelector('p').textContent=v?'내 생각을 기록했어요. 실험에서 관찰한 결과와 비교해 보세요.':'생각한 까닭을 먼저 적어 주세요.';coach.mood(v?'praise':'encourage');};e.replaceWith(wrap);});
 body.querySelectorAll('[data-reveal]').forEach(e=>{if(teach)return;e.setAttribute('role','button');e.tabIndex=0;e.onclick=()=>{e.textContent=e.dataset.reveal;coach.mood('explain');};e.onkeydown=k=>{if(k.key==='Enter')e.click();};});
 body.querySelectorAll('[data-quick]').forEach(e=>e.onclick=()=>{body.querySelector('.quick-result').textContent=e.dataset.quick==='비례'?'표와 그래프에서 비례 관계를 확인했어요.':'같은 배수로 늘어나는 관계인지 다시 살펴보세요.';coach.mood(e.dataset.quick==='비례'?'praise':'encourage');});
 body.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openActivity(b.dataset.action));
 if(teach&&s.question)body.querySelectorAll('[data-answer-field]').forEach(e=>e.disabled=true);
 restore(body);updateReveal();
}
function render(){const s=slides[current],p=currentPage();$('#slide-title').textContent=s.title;$('#slide-kicker').textContent=String(s.lesson).padStart(2,'0')+' · '+s.kicker;$('#slide-body').innerHTML=s.html;$('#slide-body').scrollTop=0;$('#slide-count').textContent=(current+1)+' / '+slides.length;$('#class-select').value=current;$('#slide-stage').textContent=teach?'→ / 스페이스: 단계 공개 · N: 강사 노트':'내 생각을 기록하고, 직접 확인해요';$('#class-prev').disabled=current===0;$('#class-next').disabled=false;$('#slide-lab').hidden=!s.action;$('#slide-lab').textContent=s.action?('↗ '+(activityNames[s.action]||'교재 실험 열기')):'';$('#slide-check').hidden=teach||!s.question||s.question.kind==='graph';$('#class-notes p').textContent=p.teacher;$('#book-link').href='./'+(teach?'teacher':'student')+'.html?s='+p.id;document.querySelectorAll('[data-lesson]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.lesson)===s.lesson));prepareSlide();coach.preview(speechText(p),p.id==='l1-future'?'surprise':s.question?'think':'listen');$('#class-read').textContent=s.question?'이 평가 지면 읽기':'이 지면 전체 읽기';save('class-current:'+ (teach?'teach':'self'),s.id);fit();}
function navigate(i){if(i<0||i>=slides.length)return;coach.stop();closeActivity();current=i;strokes=[];drawInk();render();const u=new URL(location.href);u.searchParams.set('slide',slides[i].id);u.searchParams.delete('s');history.replaceState({},'',u);}
async function narrate(){if(coach.playing){coach.stop();return;}started=true;const p=currentPage(),i=current;const completed=await coach.say(speechText(p),{id:p.id,expression:p.assessment?'think':'explain'});if(completed&&current===i&&$('#class-auto').checked&&!p.assessment&&slides[current].action)await openActivity(slides[current].action);}
async function readPage(){started=true;await coach.say(currentPage().title.replace(/\n/g,' '),{id:'full:'+currentPage().id});}
function status(t){$('#activity-status').textContent=t;if(/오류|다시/.test(t))coach.mood('encourage');else if(/기록|맞|확인했/.test(t))coach.mood('praise');}
async function openActivity(kind){coach.stop();penOff();active?.destroy();active=null;const t=++token;$('#class-workspace').classList.add('activity-open');$('#class-activity').setAttribute('aria-hidden','false');$('#class-activity-title').textContent=activityNames[kind]||'실험';$('#activity-content').innerHTML='';$('#activity-status').textContent='';window.__lab=null;fit();
 const ctx={say:(text,id)=>coach.say(text,{id}),respond:(id,text,mood)=>coach.respond(id,text,mood),status,load,save,writable,setLab:l=>window.__lab=l,auto:false,open:openActivity};
 try{const a=await mountActivity(kind,$('#activity-content'),ctx);if(token!==t)a?.destroy();else active=a;}catch(e){status('실험을 열지 못했습니다. '+e.message);}fit();
}
function closeActivity(){++token;active?.destroy();active=null;window.__lab=null;$('#activity-content').innerHTML='';$('#class-workspace').classList.remove('activity-open');$('#class-activity').setAttribute('aria-hidden','true');penOff();fit();}
function grade(){const q=slides[current].question;if(!q)return;const value=Array.isArray(q.answer)?q.answer.map((_,i)=>answers[q.id+'-'+i]??''):answers[q.id]??'';if((Array.isArray(value)?value:[value]).some(v=>!String(v).trim())){message('답을 먼저 작성해 주세요.');return;}const correct=gradeQuestion(q,value);results[q.id]={correct,value,time:Date.now()};save('results',results);const f=$('#slide-body .question-feedback');f.hidden=false;f.textContent=(correct?'맞았어요. ':'다시 확인해 봅시다. ')+q.why;coach.respond(correct?'question-correct':'question-retry',null,correct?'praise':'encourage');f.scrollIntoView({block:'nearest',behavior:'smooth'});}
$('#class-select').innerHTML=slides.map((s,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${s.lesson}차시 · ${esc(s.question?'문제 '+s.question.n:s.kicker)}</option>`).join('');$('#class-select').onchange=e=>navigate(+e.target.value);
$('#class-mode').value=teach?'teach':'self';$('#class-mode').onchange=e=>{coach.stop();const u=new URL(location.href);u.searchParams.set('mode',e.target.value);u.searchParams.set('slide',slides[current].id);location.href=u;};
$('#class-notes-toggle').hidden=!teach;$('#class-notes-toggle').onclick=()=>{$('#class-notes').hidden=!$('#class-notes').hidden;fit();};$('#slide-reveal').onclick=next;$('#class-next').onclick=next;$('#class-prev').onclick=()=>navigate(current-1);$('#slide-check').onclick=grade;$('#slide-lab').onclick=()=>openActivity(slides[current].action);$('#class-close').onclick=()=>{coach.stop();closeActivity();};$('#class-speak').onclick=narrate;$('#class-read').onclick=readPage;
$('#class-sound').setAttribute('aria-pressed',sound);$('#class-sound').textContent=sound?'소리 켬':'소리 끔';$('#class-sound').onclick=()=>{sound=!sound;coach.setEnabled(sound);save('sound',sound);$('#class-sound').setAttribute('aria-pressed',sound);$('#class-sound').textContent=sound?'소리 켬':'소리 끔';};
$('#hide-coach').onclick=()=>{const hide=document.body.classList.toggle('class-hide-coach');$('#hide-coach').textContent=hide?'우루사쌤 보이기':'우루사쌤 숨기기';fit();};$('#class-full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{message('전체 화면을 열지 못했습니다. 화면 맞춤은 유지됩니다.');}fit();};
$('.class-lessons').querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(slides.findIndex(s=>s.lesson===+b.dataset.lesson)));
$('#slide-body').oninput=e=>{const v=e.target;if(v.matches('[data-answer-field]')){answers[v.name]=v.value;save('answers',answers);}};
document.addEventListener('submit',e=>e.preventDefault());document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,button,a')||e.ctrlKey||e.metaKey||e.altKey)return;if($('#class-workspace').classList.contains('activity-open')&&(e.code==='Space'||['ArrowRight','ArrowLeft'].includes(e.key)))return;if(e.code==='Space'||e.key==='ArrowRight'){e.preventDefault();next();}else if(e.key==='ArrowLeft')navigate(current-1);else if(e.key.toLowerCase()==='n'&&teach)$('#class-notes-toggle').click();else if(e.key.toLowerCase()==='f')$('#class-full').click();else if(e.key==='Escape'){coach.stop();closeActivity();}});
function drawInk(){$('#class-ink').innerHTML=strokes.map(p=>`<polyline points="${p.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#bf4a39" stroke-width="2.3" stroke-linecap="round"/>`).join('');}function penOff(){pen=false;ptr=null;$('#class-ink').classList.remove('writing');$('#class-pen').setAttribute('aria-pressed','false');}
$('#class-pen').onclick=()=>{pen=!pen;$('#class-ink').classList.toggle('writing',pen);$('#class-pen').setAttribute('aria-pressed',pen);};$('#class-undo').onclick=()=>{strokes.pop();drawInk();};
function point(e){const r=$('#class-ink').getBoundingClientRect();return [Math.round((e.clientX-r.x)/r.width*1000),Math.round((e.clientY-r.y)/r.height*1000)];}$('#class-ink').onpointerdown=e=>{if(!pen||ptr!==null)return;ptr=e.pointerId;e.target.setPointerCapture(ptr);strokes.push([point(e)]);drawInk();};$('#class-ink').onpointermove=e=>{if(ptr!==e.pointerId)return;strokes.at(-1).push(point(e));drawInk();};$('#class-ink').onpointerup=$('#class-ink').onpointercancel=()=>ptr=null;
const ro=new ResizeObserver(fit);ro.observe($('.landscape-space'));addEventListener('resize',fit);document.addEventListener('visibilitychange',()=>{if(document.hidden){coach.stop();document.querySelectorAll('video').forEach(v=>v.pause());}});addEventListener('pagehide',()=>{coach.destroy();active?.destroy();ro.disconnect();});
render();await coach.ready;coach.preview(speechText(currentPage()),currentPage().assessment?'think':'listen');document.documentElement.dataset.ready='true';window.__class={slides,coach,answers,results,navigate,open:openActivity,close:closeActivity,grade,next,get current(){return current},get mode(){return teach?'teach':'self'}};
