import {q2,questionHTML} from './content.js';
import {scaleArt} from './graphics.js';
import {inquiryObjects,objectFigure} from './everyday-objects.js';
import {qrById} from './qr-map.js';
const names={student:'자습용 탐구 교재',teacher:'강사용 수업 교안',book:'앱 · 살아있는 책'};
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qr=(id,label)=>`<a class="guide-qr" href="${qrById[id].url}"><img src="./qr/${id}.png" alt="${label} QR"><span>${label}</span></a>`;
const flow=(items)=>`<div class="guide-flow">${items.map((t,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${t}</span></div>`).join('')}</div>`;
function aux(number,title,body,{teacher=false,kicker='사용 안내'}={}){return `<article class="paper guide-extra" data-extra="${number}"><div class="page-top"><strong><span class="chapter-medal">G</span>MSG 사이언스 랩 · 1·2차시</strong><em>${teacher?'INSTRUCTOR':'SELF STUDY'}</em></div><div class="page-heading"><div class="eyebrow">${kicker}</div><h1>${title}</h1></div><div class="page-body">${body}</div><footer class="page-foot"><span>${teacher?'강사용 운영 제안 · 원본 본문과 구분':'스마트북 · 실험 · 인쇄 교재'}</span><span>${teacher?'강사용':'자습용'}<strong>${String(number).padStart(2,'0')}</strong></span></footer></article>`;}
function cover(teacher){return `<article class="paper guide-cover" data-extra="cover"><div class="cover-top"><span>MSG<br><b>SCIENCE LAB</b></span><span class="cover-edition">${names[teacher?'teacher':'student']}</span></div><div class="cover-title"><p>초과심_물리 · PART I 무게 재기</p><h1>용수철과<br>무게 재기</h1><h2>생각을 먼저, 측정을 그다음.</h2></div><div class="cover-art">${scaleArt({force:12,labels:false})}<div class="cover-ring"><span>01–02</span><b>두 차시의<br>탐구 여행</b></div></div><div class="cover-objects">${inquiryObjects.map(o=>`<figure>${objectFigure(o)}<figcaption>${o.name}</figcaption></figure>`).join('')}</div>${flow(['예상하기','직접 측정','과정 점검','설명하기'])}<div class="cover-bottom"><div aria-hidden="true"></div>${qr('l1-inquiry','살아있는 책 열기')}</div><div class="cover-name">${teacher?'담당 강사':'이름'}<i></i> ${teacher?'수업일':'날짜'}<i></i></div></article>`;}
function overview(teacher){const offset=teacher?6:2;return aux(2,'한 권으로 읽고,\n직접 실험해요.',`
<div class="guide-edition-line"><b>${teacher?'강사용 교안':'자습용 교재'}</b><span>본문 → 활동 → 관찰 기록 → 다시 설명</span></div>
<section class="inquiry"><div class="eyebrow">이 책의 사용법</div><b>종이에서는 기록하고, 화면에서는 직접 움직여요.</b><ol><li>질문과 본문을 읽고 먼저 내 생각을 적습니다.</li><li>각 쪽의 QR을 찍으면 해당 실험·영상·평가가 열립니다.</li><li>측정 기록을 제출하고, 방법을 고쳐 다시 확인합니다.</li><li>처음 예상과 관찰 결과를 비교해 내 말로 설명합니다.</li></ol></section>
<h3 class="guide-ribbon">차시별 찾아보기</h3>
<table class="book-table guide-map"><thead><tr><th>차시</th><th>학습 내용</th><th>이 교재</th><th>본책</th></tr></thead><tbody>
<tr><th>01</th><td>다섯 물건 예상·측정<br>용수철저울의 구조·사용·눈높이<br>여러 저울·과거와 미래·일일평가 6문항</td><td>${offset+1}–${offset+12}쪽</td><td>10–15쪽</td></tr>
<tr><th>02</th><td>탄성·당기기·누르기<br>추의 무게와 늘어난 길이·표와 그래프<br>생활 속 도구·일일평가 12문항</td><td>${offset+13}–${offset+20+(teacher?1:0)}쪽</td><td>16–21쪽</td></tr></tbody></table>
<div class="guide-legend"><section class="legend-concept"><b>핵심 개념</b><p>초록 테두리에서 중요한 내용을 정리해요.</p></section><section class="legend-think"><b>생각·관찰·기록</b><p>남색 테두리 안에서 내 생각과 근거를 남겨요.</p></section><section class="legend-note"><b>플러스 노트</b><p>노란 박스에서 자료의 조건과 보충 설명을 확인해요.</p></section>${teacher?'<section class="legend-teacher"><b>강사 해설</b><p>붉은 박스는 정답과 지도 참고용입니다. 학생에게 미리 공개하지 않습니다.</p></section>':'<section class="legend-lab"><b>SMART LAB</b><p>초록 버튼 또는 QR로 실험과 영상에 연결해요.</p></section>'}</div>
<div class="editor-note"><b>두 종류의 자료를 구분해요.</b><p>본책을 재편집한 18쪽과 추가 도입 탐구 2쪽으로 구성했습니다. 생활 물건의 무게는 가상 설정값이며, 본책 실험값이나 실제 제품 실측값이 아닙니다.</p></div>
${teacher?'<p class="guide-small">앱 강사용 화면은 처음에는 정답을 숨깁니다. ‘교안·정답 공개’를 눌렀을 때만 해설이 나타납니다. 자습용 링크로 이동하면 다시 숨겨집니다.</p>':'<p class="guide-small">앱에서 처음 ‘수업 시작’을 누르면 소리 재생이 시작됩니다. 해설 뒤 활동은 자동으로 이어지고, 내가 답하거나 조작할 때는 멈춥니다.</p>'}
`,{teacher,kicker:'READ · OBSERVE · RECORD'});}
const plans={1:{goal:'저울이 필요한 이유를 설명하고, 용수철저울의 구조·사용 순서·눈높이를 연결합니다.',kit:'신발 한 짝, 사과 한 개, 귤 두 개 한 묶음, 휴대폰 한 개, 필기구가 든 필통. 앱 실험 또는 적절한 범위의 실제 저울과 같은 받침을 준비합니다.',rows:[['예상','다섯 물건의 수량과 내용물을 먼저 확인하고 모두 줄 세웁니다. 예상의 까닭을 적은 뒤 측정합니다.','크기와 모양만으로 무게를 알 수 있을까요?'],['측정·점검','처음에는 영점 정오를 알려주거나 자동 보정하지 않습니다. 방법 오류는 제출 뒤 중립적인 문장으로만 알립니다.','어떤 과정을 다시 살펴봐야 할까요?'],['구조·사용','부품 확대와 이름 맞히기, 영점 조절, 표시자 안정과 눈높이를 학습합니다.','표시자가 없다면 무엇이 어려울까요?'],['읽기·영상','저울의 종류와 용수철의 과거·미래를 본문과 함께 읽습니다. 기록영상과 개념 도해를 구분합니다.','영상에서 용수철은 어떤 일을 했나요?'],['평가·정리','원본 6문항을 푼 뒤 관련 실험·확인 질문으로 돌아갑니다.','처음 생각에서 무엇이 달라졌나요?']]},2:{goal:'힘에 따른 변형을 관찰하고, 추의 무게와 늘어난 길이를 표·그래프로 연결합니다.',kit:'앱의 당기기·압축 모형, 추의 무게별 길이 측정, 그래프 활동. 종이 교재·필기도구를 함께 사용합니다.',rows:[['변형 관찰','잡아당기거나 누른 뒤 힘을 없앴을 때의 변화를 관찰합니다.','전체 길이와 변한 길이는 어떻게 다른가요?'],['측정·표','본문 표의 10·20·30 g → 3·6·9 cm를 사용합니다.','무엇을 같게 두고 무엇을 바꾸었나요?'],['그래프','가로축과 세로축을 확인한 뒤 점을 직접 찍습니다.','추가 두 배가 되면 늘어난 길이는요?'],['도구·조건','재질·철사 굵기·코일 지름과 여섯 도구의 역할을 본문에 맞춰 비교합니다.','용수철이 없다면 이 도구는 어떻게 될까요?'],['평가·정리','원본 12문항. 마지막 그래프는 4·8·12 cm 자료임을 분리해 확인합니다.','이번 표는 앞의 실험과 무엇이 다른가요?']]}};
function plan(lesson,num){const d=plans[lesson];return aux(num,`${lesson}차시\n수업 운영 한눈에`, `<section class="definition"><b>목표</b><p>${d.goal}</p></section><div class="editor-note"><b>준비와 연결</b><p>${d.kit}</p></div><h3 class="guide-ribbon">수업 흐름 · 시간은 학급에 맞춰 조절</h3><div class="guide-sequence">${d.rows.map(([a,b,c],i)=>`<section><span>${i+1}</span><div><h3>${a}</h3><p>${b}</p><blockquote>${c}</blockquote></div></section>`).join('')}</div><div class="guide-plan-foot">${qr(lesson===1?'l1-inquiry':'l2-elastic','이 차시 활동 열기')}<p>이 페이지는 <b>강사용 운영 제안</b>입니다.<br>원본 본문과 평가의 내용을 대신하지 않습니다.</p></div>`,{teacher:true,kicker:'INSTRUCTOR · 수업 진행안'});}
function notes(lesson,num,pages){const ps=pages.filter(p=>p.lesson===lesson);return aux(num,`${lesson}차시\n지도 포인트와 점검`, `<p class="guide-small">현재 교안에 포함된 페이지별 진행 메모입니다. 학생 화면의 답은 필요할 때만 공개합니다.</p><div class="guide-note-list">${ps.map((p,i)=>`<section><b>${String(i+1).padStart(2,'0')} · ${p.kicker.split('·').at(-1).trim()}</b><p>${safe(p.teacher)}</p></section>`).join('')}</div>`,{teacher:true,kicker:'TEACHER NOTES · 페이지별 메모'});}
export function frontMatter(teacher,pages){return cover(teacher)+overview(teacher)+(teacher?plan(1,3)+plan(2,4)+notes(1,5,pages)+notes(2,6,pages):'');}
export function frontMatterCount(teacher){return teacher?6:2;}
export function editionName(kind){return names[kind]||names.book;}

// Give the dense instructor assessment a second sheet instead of tiny answers.
export function printablePages(pages,teacher){return teacher?pages.flatMap(p=>p.id==='l2-test-b'?[{...p,title:'개념을 확인해요.\n강사 해설 ①',lead:'2차시 · 원본 5~8번',printClass:'teacher-test-split',body:'<div class="test-grid">'+q2.slice(4,8).map(q=>questionHTML(q)).join('')+'</div>'},{...p,title:'조건을 확인해요.\n강사 해설 ②',lead:'2차시 · 원본 9~11번',printClass:'teacher-test-split',body:q2.slice(8,11).map(q=>questionHTML(q)).join('')}]:p):pages;}
