import {inquiryObjects,objectFigure} from './inquiry.js';
const figures=items=>`<div class="print-objects">${items.map(o=>`<figure>${objectFigure(o)}<figcaption>${o.name}</figcaption></figure>`).join('')}</div>`;
export const inquiryPages=[
 {id:'l1-inquiry',lesson:1,source:[10],layoutIndex:'intro-a',added:true,kicker:'PREDICT · 추가 도입 탐구',title:'저울이\n왜 필요할까요?',lead:'다르게 생긴 두 물건과 비슷한 세 물건, 먼저 예상해요.',action:'inquiry',teacher:'먼저 예상과 근거를 수집합니다. 측정 전이나 나사 조절 직후에 영점의 정오 여부를 알려주지 않습니다. 실제 제출 과정에 오류가 있을 때만 실험 방법 오류라고 안내합니다.',body:`<section class="unit-section"><h3><span>01</span>어느 것이 더 무거울까요?</h3><p>큰 물건이 언제나 더 무거울까요? 두 물건을 보고 먼저 생각해 보세요.</p>${figures(inquiryObjects.slice(0,2))}<div class="print-choice">□ 큰 상자　 □ 작은 금속 추　 □ 아직 판단하기 어려워요</div></section><section class="inquiry"><b>그렇게 생각한 까닭은 무엇인가요?</b><div class="write-lines"><i></i><i></i></div></section><section class="unit-section"><h3><span>02</span>비슷한 물건도 비교할 수 있을까요?</h3><p>다음 쪽의 주머니 세 개는 무게가 비슷합니다. 눈으로만 보고 순서를 정할 수 있을까요?</p></section><div class="editor-note"><b>이번 탐구의 약속</b><p>먼저 예상을 기록하고, 그다음 직접 측정합니다. 예상이 틀렸다는 이유만으로 실험 방법이 잘못됐다고 판단하지 않습니다.</p></div><button class="page-action" data-action="inquiry">↗ 예상 · 줄 세우기 · 저울 실험</button><div class="teacher-answer">교사용 가상 설정: 큰 상자 4 N, 작은 금속 추 18 N. 실제 물건의 일반적인 무게라는 뜻은 아닙니다. 처음에는 수치를 공개하지 않습니다.</div>`},
 {id:'l1-inquiry-record',lesson:1,source:[10],layoutIndex:'intro-b',added:true,kicker:'MEASURE & REFLECT · 추가 도입 탐구',title:'예상한 순서를\n측정으로 확인해요.',lead:'비슷한 세 물건 줄 세우기 → 측정 → 실험 과정 점검',action:'inquiry',teacher:'순서가 맞더라도 공통 영점 오차가 있으면 값은 잘못될 수 있습니다. 원인을 알려주는 대신 학생이 방법을 설명하고 재실험하게 합니다. 올바른 재측정을 마친 뒤 원인을 공개합니다.',body:`${figures(inquiryObjects.slice(2))}<div class="print-choice"><b>가벼울 것 같은 순서 → 무거울 것 같은 순서</b><p>(　　　　) → (　　　　) → (　　　　)</p>□ 이 순서가 맞는지 확신하기 어려워요.</div><table class="book-table inquiry-log"><thead><tr><th>물건</th><th>처음 측정 (N)</th><th>다시 측정 (N)</th></tr></thead><tbody>${inquiryObjects.map(o=>`<tr><th>${o.name}</th><td></td><td></td></tr>`).join('')}</tbody></table><section class="inquiry"><b>“실험 방법에 오류가 있어요.” 어떤 과정을 다시 확인할까요?</b><div class="write-lines"><i></i><i></i></div></section><section class="inquiry"><b>그래서 저울은 왜 필요할까요?</b><div class="write-lines"><i></i><i></i></div></section><button class="page-action" data-action="inquiry">↗ 나의 예상과 실험 기록 열기</button><div class="teacher-answer">가상 설정: B 10 N &lt; A 11 N &lt; C 12 N. 과정 오류: 기준 불일치, 물체를 단 채 조절, 진동 중 기록, 비스듬한 시선, 눈금과 기록 불일치. 학생에게는 처음부터 원인을 공개하지 않습니다.</div>`}
];
export const inquiryNarration={
 'l1-inquiry':'저울은 왜 필요할까요? 먼저 다르게 생긴 두 물건 중 어느 것이 더 무거울지 예상해요. 다음에는 비슷한 세 주머니도 가벼운 순서대로 놓아 봅시다. 생각한 까닭을 말한 뒤 저울로 확인해 볼까요?',
 'l1-inquiry-record':'예상한 순서를 측정으로 확인해 봅시다. 실험 방법에 오류가 있다는 안내가 나오면, 무엇을 다시 확인해야 할지 스스로 생각해 보세요. 원인을 찾아 다시 실험한 다음, 처음 결과와 비교합니다.'
};
