import {inquiryObjects,objectFigure,formatForce} from './everyday-objects.js';
const figures=()=>`<div class="print-objects everyday-print-objects">${inquiryObjects.map(o=>`<figure>${objectFigure(o)}<figcaption>${o.name}</figcaption></figure>`).join('')}</div>`;
const blankRank=()=>'<div class="five-rank-blanks">'+Array.from({length:5},(_,i)=>`<span><b>${i+1}</b>（　　　　　）</span>`).join('<i>→</i>')+'</div>';
export const inquiryPages=[
 {id:'l1-inquiry',lesson:1,source:[10],layoutIndex:'intro-a',added:true,kicker:'PREDICT · 생활 물건 다섯 가지',title:'저울이\n왜 필요할까요?',lead:'모양은 달라도 무게가 비슷해요. 다섯 물건 전체를 줄 세워요.',action:'inquiry',teacher:'익숙한 물건의 수량과 내용물을 정확히 확인시킵니다. 신발 한 짝·사과 한 개·귤 두 개 한 묶음·휴대폰 한 개·필기구가 든 필통, 비교 항목은 총 다섯 개입니다. 측정 전에는 무게나 영점 정오 여부를 알려주지 않습니다.',body:`<section class="unit-section"><h3><span>01</span>어느 것이 더 무거울까요?</h3><p>크기와 모양만 보고 무게를 정확히 비교할 수 있을까요?</p>${figures()}<p class="everyday-print-note">귤 두 개는 따로 줄 세우지 않고 <b>한 묶음</b>으로 재요. 필통은 안에 든 필기구까지 함께 잽니다.</p></section><section class="inquiry"><b>다섯 물건을 가벼울 것 같은 순서대로 써 보세요.</b>${blankRank()}<p class="everyday-print-note">□ 순서를 아직 확신하기 어려워요.</p></section><section class="inquiry"><b>무엇을 보고 그렇게 예상했나요?</b><div class="write-lines"><i></i><i></i></div></section><div class="editor-note"><b>눈으로 예상한 뒤, 저울로 확인해요.</b><p>예상 순서와 까닭을 먼저 기록합니다. 다섯 물건은 같은 투명 받침에 놓아 비교하고, 내용물을 감추지 않습니다.</p></div><button class="page-action" data-action="inquiry">↗ 다섯 물건 줄 세우기 · 직접 측정</button><div class="teacher-answer">추가 가상 탐구용 설정값: ${inquiryObjects.map(o=>`${o.name} ${formatForce(o.force)} N`).join(' / ')}. 실제 제품의 실측값이 아닙니다. 0~5 N 저울, 작은 눈금 0.1 N을 사용합니다. 본책의 교구·자료는 바꾸지 않습니다.</div>`},
 {id:'l1-inquiry-record',lesson:1,source:[10],layoutIndex:'intro-b',added:true,kicker:'MEASURE & REFLECT · 다섯 물건 모두 측정',title:'예상한 순서를\n측정으로 확인해요.',lead:'다섯 물건 하나씩 측정 → 과정 점검 → 예상과 비교',action:'inquiry',teacher:'큰 물건이 무겁다는 생각을 정답처럼 강화하지 않습니다. 다섯 물건의 무게 차이가 작으므로 한 눈금의 크기를 읽고 정확히 기록하는 이유를 묻습니다. 실험 전 정오 안내나 자동 영점 조절 없이, 제출 후 방법 오류를 찾게 합니다.',body:`<table class="book-table inquiry-log everyday-record-table"><thead><tr><th>비교할 물건</th><th>처음 측정 (N)</th><th>다시 측정 (N)</th></tr></thead><tbody>${inquiryObjects.map(o=>`<tr><th><span class="record-object-icon">${objectFigure(o)}</span>${o.name}</th><td></td><td></td></tr>`).join('')}</tbody></table><section class="inquiry"><b>측정한 결과, 가벼운 순서대로 다시 써 보세요.</b>${blankRank()}</section><section class="inquiry"><b>“실험 방법에 오류가 있어요.” 어떤 과정을 다시 확인할까요?</b><div class="write-lines"><i></i><i></i></div></section><section class="inquiry"><b>처음 예상과 비교해 보세요. 그래서 저울은 왜 필요할까요?</b><div class="write-lines"><i></i><i></i></div></section><button class="page-action" data-action="inquiry">↗ 다섯 물건의 예상·측정 기록 열기</button><div class="teacher-answer">이 샘플의 결과: 귤 두 개 1.8 N &lt; 사과 2.0 N &lt; 휴대폰 2.2 N &lt; 신발 한 짝 2.4 N &lt; 필기구가 든 필통 2.6 N. 같은 받침의 무게는 제외한 가상 설정입니다. 실제 물건은 크기·제품·내용물에 따라 달라집니다. 방법 오류의 원인은 올바른 재측정 뒤 마지막 해설에서 공개합니다.</div>`}
];
export const inquiryNarration={
 'l1-inquiry':'저울은 왜 필요할까요? 신발 한 짝, 사과 한 개, 귤 두 개, 휴대폰 한 개, 그리고 필기구가 든 필통을 준비했어요. 모양은 달라도 무게가 비슷한 다섯 물건이에요. 귤 두 개는 한 묶음으로 생각하고, 다섯 물건 전체를 가벼울 것 같은 순서대로 놓아 봅시다. 까닭을 말한 뒤 저울로 확인해 볼까요?',
 'l1-inquiry-record':'다섯 물건을 하나씩 재고 처음 예상과 비교해 봅시다. 실험 방법에 오류가 있다는 안내가 나오면 어떤 과정을 다시 확인할지 스스로 생각해 보세요. 다시 측정한 다음 다섯 물건 전체를 가벼운 순서대로 정리합니다.'
};
