import {objectSets,objects,forceFor,initialInquiry,isPermutation,makeRecord,latestRecords,inspectRound,measuredOrder,genericMethodFeedback} from './inquiry-model.js';
import {inquiryObjectArt as art} from './inquiry-art.js';
import {esc} from './graphics.js';
const KEY='inquiry-ranking-v1';
export async function mountInquiry(host,ctx){
 let disposed=false,lab=null,selected=null,dragCancel=()=>{},state=ctx.load(KEY,null);
 if(!state||state.version!==1||!isPermutation(state.prediction))state=initialInquiry();
 const persist=()=>ctx.save(KEY,state),status=t=>{if(!disposed)ctx.status(t);};
 const stopLab=()=>{dragCancel();lab?.destroy();lab=null;ctx.setLab(null);};
 function render(){stopLab();host.innerHTML='<div class="inquiry-work"></div>';const root=host.firstElementChild;
  if(state.phase==='pair')pair(root);else if(state.phase==='rank')rank(root);else measurement(root);
 }
 function pair(root){root.innerHTML=`<div class="inquiry-heading"><span>1 / 3 · 먼저 예상하기</span><h3>어느 것이 더 무거울까요?</h3><p>정답을 찾기 전에, 내 생각과 이유를 남겨요.</p></div><div class="object-choices">${objectSets.pair.map(o=>`<button data-pair="${o.id}" aria-pressed="${state.pair===o.id}">${art(o.id)}<strong>${o.name}</strong></button>`).join('')}</div><button class="unsure" data-pair="unsure" aria-pressed="${state.pair==='unsure'}">아직 모르겠어요</button><label class="inquiry-label">그렇게 생각한 까닭<textarea data-why rows="2" maxlength="500" placeholder="겉모양, 들어 본 느낌, 경험을 바탕으로 설명해요.">${esc(state.why)}</textarea></label><button class="inquiry-next" data-pair-next>예상 남기고, 세 물건 줄 세우기 →</button><small class="inquiry-footnote">서로 다른 무게를 가진 가상 물건입니다. 실제 제품의 무게를 뜻하지 않습니다.</small>`;
  root.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{state.pair=b.dataset.pair;persist();root.querySelectorAll('[data-pair]').forEach(x=>x.setAttribute('aria-pressed',x===b));status('예상을 남겼어요. 아직 정답을 공개하지 않습니다.');});
  root.querySelector('[data-why]').oninput=e=>{state.why=e.target.value;persist();};
  root.querySelector('[data-pair-next]').onclick=()=>{if(!state.pair){status('예상을 하나 골라 주세요. 아직 모르겠어요를 골라도 됩니다.');return;}if(!state.why.trim()){status('그렇게 생각한 까닭도 한 문장 남겨 주세요.');return;}state.phase='rank';persist();render();status('이번에는 비슷한 세 물건입니다.');};
 }
 function rank(root){root.innerHTML=`<div class="inquiry-heading"><span>2 / 3 · 가벼운 쪽부터 예상</span><h3>비슷하게 생긴 필통 세 개를<br>줄 세워 볼까요?</h3><p>잡아서 옮기거나 이동 버튼으로 순서를 바꿉니다. 무게는 아직 보여 주지 않아요.</p></div><div class="rank-direction"><b>가벼울 것 같은 쪽</b><span>→</span><b>무거울 것 같은 쪽</b></div><div class="rank-tray" aria-label="예상 순서"></div><label class="inquiry-label">순서를 정한 이유 또는 아직 확신하기 어려운 까닭<textarea data-rank-why maxlength="500" rows="2">${esc(state.rankWhy)}</textarea></label><div class="inquiry-button-row"><button data-back>두 물건 예상으로</button><button class="inquiry-next" data-rank-next>이 예상을 남기고 저울로 확인 →</button></div>`;
  const tray=root.querySelector('.rank-tray');function draw(){tray.innerHTML=state.prediction.map((id,i)=>`<article class="rank-card" data-rank-id="${id}"><div class="rank-handle" data-drag-id="${id}" role="button" tabindex="0" aria-label="필통 ${id} 잡아 이동">${art(id)}<strong>${i+1}번째 · 필통 ${id}</strong></div><div><button data-move="${id}" data-dir="-1" ${i===0?'disabled':''} aria-label="필통 ${id} 앞으로">←</button><button data-move="${id}" data-dir="1" ${i===2?'disabled':''} aria-label="필통 ${id} 뒤로">→</button></div></article>`).join('');
   tray.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.move,+b.dataset.dir));
   tray.querySelectorAll('[data-drag-id]').forEach(h=>{let d=null;h.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;h.setPointerCapture(e.pointerId);d={x:e.clientX,y:e.clientY,id:e.pointerId};h.classList.add('dragging');};h.onpointerup=e=>{if(!d||e.pointerId!==d.id)return;const cards=[...tray.querySelectorAll('[data-rank-id]')],nearest=cards.reduce((best,c)=>{const r=c.getBoundingClientRect(),dist=Math.hypot(e.clientX-(r.x+r.width/2),e.clientY-(r.y+r.height/2));return !best||dist<best.dist?{id:c.dataset.rankId,dist}:best;},null);h.classList.remove('dragging');if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>8&&nearest){const from=state.prediction.indexOf(h.dataset.dragId),to=state.prediction.indexOf(nearest.id);const a=[...state.prediction],item=a.splice(from,1)[0];a.splice(to,0,item);state.prediction=a;persist();draw();status('예상 순서를 바꾸었어요.');}d=null;};h.onpointercancel=()=>{d=null;h.classList.remove('dragging');};h.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(h.dataset.dragId,e.key==='ArrowLeft'?-1:1);}};});
  }
  function move(id,d){const from=state.prediction.indexOf(id),to=from+d;if(to<0||to>2)return;const a=[...state.prediction];[a[from],a[to]]=[a[to],a[from]];state.prediction=a;persist();draw();status('예상 순서: '+a.map(x=>'필통 '+x).join(' → '));}
  root.querySelector('[data-rank-why]').oninput=e=>{state.rankWhy=e.target.value;persist();};root.querySelector('[data-back]').onclick=()=>{state.phase='pair';persist();render();};
  root.querySelector('[data-rank-next]').onclick=()=>{if(!state.rankWhy.trim()){status('왜 그 순서로 정했는지, 또는 왜 어려운지 적어 주세요.');return;}state.lockedPrediction=[...state.prediction];state.phase='measure';persist();render();status('직접 정한 방법으로 측정하고 읽은 값을 기록해 보세요.');};draw();
 }
 async function measurement(root){root.innerHTML=`<div class="inquiry-lab lab-layout"><div class="scene"></div><div class="lab-controls inquiry-controls"><span class="inquiry-step">3 / 3 · ${state.round}차 측정</span><h3>읽은 값을 그대로 기록해요.</h3><div class="locked-prediction"><b>처음 예상</b><span>${state.pair==='unsure'?'두 물건은 아직 모르겠어요':(objects.find(o=>o.id===state.pair)?.name||'')+'이 더 무거울 것 같아요.'}</span><span>${state.lockedPrediction.map(x=>'필통 '+x).join(' → ')}</span></div><div class="inquiry-loads">${objects.map(o=>`<button data-inquiry-load="${o.id}" aria-label="${o.name} 매달기">${art(o.id)}<span>${o.name}</span></button>`).join('')}</div><p class="inquiry-instruction">물건을 고리로 끌어 놓거나 눌러 매답니다. 눈금판을 눌러 값을 고르거나 직접 입력하세요.</p><div class="inquiry-button-row"><button data-remove>물체 빼기</button><button data-adjust="-1" aria-label="조절나사 왼쪽으로">나사 −</button><button data-adjust="1" aria-label="조절나사 오른쪽으로">나사 +</button></div><div class="inquiry-button-row viewpoint"><button data-view="high">위에서</button><button data-view="front">앞에서</button><button data-view="low">아래에서</button></div><label class="inquiry-label">내가 읽은 값 <input data-observation type="number" min="0" max="30" step="1" aria-label="읽은 눈금 N"> N</label><button class="inquiry-next" data-record>측정값 기록</button><div class="inquiry-records" data-records></div><button data-inspect>실험 결과 제출 · 방법 점검</button><section class="inquiry-review" data-review></section><details class="teacher-only teacher-audit"><summary>교사용 · 실제 조작 기록</summary><div data-audit></div></details><small class="inquiry-footnote">가상 저울 0~30 N · 눈금 1 N. 기록은 이 브라우저에 저장됩니다.</small></div></div>`;
  const panel=root.querySelector('.inquiry-controls'),scene=root.querySelector('.scene');
  const {mountLab}=await import('./lab3d.js');if(disposed||!root.isConnected)return;
  let lastZero=state.zero;
  lab=mountLab(scene,{mode:'inquiry',initialZero:state.zero,onChange:s=>{if(disposed)return;if(s.zero!==lastZero){state.zero=s.zero;lastZero=s.zero;persist();}},onAdjustZero:s=>{state.events.push({type:'adjust',zero:s.zero,force:s.force,round:state.round,time:Date.now()});state.zero=s.zero;persist();},onPick:v=>{panel.querySelector('[data-observation]').value=v;status(`내가 고른 눈금: ${v} N. 기록하려면 측정값 기록을 누르세요.`);}});ctx.setLab(lab);
  function load(id){selected=id;lab.setForce(forceFor(id),{shape:objects.find(o=>o.id===id).shape});panel.querySelector('[data-observation]').value='';panel.querySelectorAll('[data-inquiry-load]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.inquiryLoad===id));state.events.push({type:'load',id,round:state.round,time:Date.now()});persist();status(objects.find(o=>o.id===id).name+'을 매달았어요. 원하는 방법으로 관찰하고 기록해요.');}
  const cancels=[];panel.querySelectorAll('[data-inquiry-load]').forEach(b=>{let drag=null;b.addEventListener('click',e=>{if(e.detail===0)load(b.dataset.inquiryLoad);});b.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;b.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,id:e.pointerId,g:null};e.preventDefault();};b.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;if(!drag.g&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8){drag.g=document.createElement('div');drag.g.className='drag-ghost';drag.g.textContent=b.textContent.trim();document.body.append(drag.g);}if(drag.g){drag.g.style.left=e.clientX+8+'px';drag.g.style.top=e.clientY-18+'px';}};b.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const h=lab.hookScreen();if(!drag.g||Math.hypot(e.clientX-h.x,e.clientY-h.y)<95)load(b.dataset.inquiryLoad);else status('고리 가까이에 물건을 놓아 주세요.');drag.g?.remove();drag=null;};const cancel=()=>{drag?.g?.remove();drag=null;};b.onpointercancel=cancel;cancels.push(cancel);});dragCancel=()=>cancels.forEach(f=>f());
  panel.querySelector('[data-remove]').onclick=()=>{lab.setForce(0);selected=null;state.events.push({type:'remove',round:state.round,time:Date.now()});persist();status('물체를 뺐어요.');};
  panel.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>{lab.setZero(lab.state().zero+Number(b.dataset.adjust));status('조절나사를 움직였어요.');});
  panel.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{lab.setEye(b.dataset.view);status('관찰 위치를 바꾸었어요.');});
  function table(){const rounds=[...new Set(state.records.map(r=>r.round))];panel.querySelector('[data-records]').innerHTML=rounds.length?rounds.map(round=>{const latest=latestRecords(state.records,round);return `<table><caption>${round}차 · 내가 기록한 값</caption><tr><th>물건</th><th>N</th></tr>${objects.map(o=>`<tr><td>${o.name}</td><td>${latest.has(o.id)?latest.get(o.id).entered:'—'}</td></tr>`).join('')}</table>`;}).join(''):'<p>아직 측정 기록이 없어요.</p>';}
  function auditTeacher(){const report=inspectRound(state),labels={'initial-reference':'빈 저울의 기준 오차','moving-indicator':'진동 중 기록','viewpoint':'시점 또는 시점 이동 중 기록','reading-or-recording':'관찰값과 입력값의 차이','loaded-adjustment':'물체를 단 채 조절'};panel.querySelector('[data-audit]').textContent=report.issues.map(i=>(objects.find(o=>o.id===i.id)?.name||'절차')+': '+labels[i.code]).join(' / ')||'현재 기록에서 확인된 방법 오류 없음';}
  panel.querySelector('[data-record]').onclick=()=>{if(!selected){status('먼저 물건을 하나 매달아 주세요.');return;}const input=panel.querySelector('[data-observation]');if(input.value===''||!input.checkValidity()){status('읽은 값을 0~30 N 사이의 숫자로 적어 주세요.');return;}state.records.push(makeRecord(selected,Number(input.value),lab.state(),state.round));state.reviewed=false;state.finished=false;persist();table();panel.querySelector('[data-review]').replaceChildren();status('측정값을 기록했어요. 기록을 모두 모은 뒤 실험 방법을 점검합니다.');};
  panel.querySelector('[data-inspect]').onclick=()=>{const report=inspectRound(state);if(!report.complete){status('아직 기록하지 않은 물건이 있어요: '+report.missing.map(id=>objects.find(o=>o.id===id).name).join(', '));return;}state.reviewed=true;persist();review();auditTeacher();status(report.valid?'측정 기록을 모았어요. 예상과 결과를 비교하고, 저울이 왜 필요한지 설명해 보세요.':genericMethodFeedback);};
  function review(){const el=panel.querySelector('[data-review]');if(!state.reviewed){el.replaceChildren();return;}const report=inspectRound(state);
   if(!report.valid){el.innerHTML=`<h4>실험 방법을 돌아봐요</h4><p>${genericMethodFeedback}</p><p>준비 → 매달기 → 관찰 → 읽기 → 기록</p><label>내가 점검할 절차와 바꿀 방법<textarea data-method rows="3" maxlength="1000">${esc(state.methodNote)}</textarea></label><button data-retest>방법을 바꾸어 다시 측정</button>`;el.querySelector('[data-method]').oninput=e=>{state.methodNote=e.target.value;persist();};el.querySelector('[data-retest]').onclick=()=>{if(!state.methodNote.trim()){status('내가 점검한 절차나 바꾸려는 방법을 먼저 적어 주세요.');return;}state.roundNotes.push({round:state.round,text:state.methodNote});state.round++;state.methodNote='';state.reviewed=false;state.finished=false;persist();render();status('이전 기록은 그대로 남겨 두었어요. 방법을 바꾸어 다시 측정해 봅시다.');};
   }else {const order=measuredOrder(state),m=latestRecords(state.records,state.round);el.innerHTML=`<h4>예상과 측정 결과를 비교해요</h4><p>처음 예상: ${state.lockedPrediction.join(' → ')}<br>측정 뒤: <b>${order.join(' → ')}</b></p><p>스펀지 공 ${m.get('foam').entered} N / 두꺼운 책 ${m.get('book').entered} N</p><label>저울이 왜 필요했나요? 내 기록을 근거로 설명해요.<textarea data-conclusion rows="3" maxlength="1000">${esc(state.conclusion)}</textarea></label><button data-finish>탐구 설명 남기기</button><p data-finished>${state.finished?'내 예상·측정·방법 점검·설명을 모두 남겼어요.':''}</p>`;el.querySelector('[data-conclusion]').oninput=e=>{state.conclusion=e.target.value;persist();};el.querySelector('[data-finish]').onclick=()=>{if(!state.conclusion.trim()){status('내 기록을 근거로 한 설명을 남겨 주세요.');return;}state.finished=true;persist();el.querySelector('[data-finished]').textContent='내 예상·측정·방법 점검·설명을 모두 남겼어요.';status('탐구 기록을 남겼어요. 예상이 달라져도 괜찮아요. 측정한 증거로 설명한 것이 중요합니다.');};}
  }
  table();review();if(state.reviewed)auditTeacher();
 }
 render();return {destroy(){disposed=true;stopLab();}};
}
